seed: 42
data:
  dataset: rvtall
  root: data/RVTALL/Processed_sliced_data
  modalities: [video, mmwave, uwb, laser, audio]
  fps: 25
  sequence_seconds: 2.0
  tiny: true
  num_workers: 2
  video:
    frames: 8
    size: 112
  radar:
    size: 64
  uwb:
    size: 64
  laser:
    size: 256
  audio:
    sr: 16000
model:
  latent_dim: 128
  temperature: 0.07
  fusion: attention
train:
  batch_size: 2
  max_epochs: 1
  lr: 3e-4
  weight_decay: 1e-4
  precision: 32
eval:
  retrieval_k: [1,5,10]
  save_dir: outputs/rvtall_contrastive_tiny
